name = "MIPVerify"
uuid = "e5e5f8be-2a6a-5994-adbb-5afbd0e30425"
authors = ["Vincent Tjeng <vincent.tjeng@gmail.com>"]
version = "0.3.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
CSV = "0.7, 0.8, 0.9, 0.10"
Cbc = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0"
DataFrames = "0.21, 0.22, 1"
DocStringExtensions = "0.8, 0.9"
IntervalArithmetic = "0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20"
JuMP = "0.21.4, 0.21.5, 0.22, 0.23, 1"
MAT = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10"
MathOptInterface = "0.9, 0.10, 1"
Memento = "0.12, 0.13, 1"
ProgressMeter = "1"
TimerOutputs = "0.5"
julia = "1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Statistics", "Test", "Cbc", "TimerOutputs"]
